# Generated by Django 2.2 on 2021-04-07 00:15

from django.db import migrations, models
import django.db.models.deletion

import db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loggi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', db.SpanningForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loggi.Father')),
            ],
        ),
    ]
